name: Extract and Translate Documents

on:
  workflow_dispatch:

jobs:
  extract_and_translate:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.x'
      VENV_DIR: env
      DOCUMENT_PDF: path/to/your/document.pdf
      DOCUMENT_EPUB: books/Islam_et_judéo-christianisme_Ellul_Jacques.epub
      REPO_DIR: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m venv ${{ env.VENV_DIR }}
          python -m pip install --upgrade pip
          source ${{ env.VENV_DIR }}/bin/activate
          pip install pdfplumber ebooklib requests pandas openai transformers
          
      - name: Extract and translate EPUB
       # if: startsWith(github.event.head_commit.message, 'Translate EPUB')
        env:
          OPENAI_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        run: |
          source env/bin/activate
          python main.py show-chapters --input yourbook.epub
          python main.py translate --input yourbook.epub --output translatedbook.epub --config config.yaml --from-lang EN --to-lang PL
          python src/translate-cookbook.py ${{ env.DOCUMENT_EPUB }} epub
